# Generated by Django 4.2.3 on 2023-08-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propertease", "0003_alter_propertycategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
