# Generated by Django 4.2.3 on 2023-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertease", "0004_remove_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.CharField(max_length=256),
        ),
    ]
