# Generated by Django 4.2.3 on 2023-08-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propertease", "0007_alter_comment_author_alter_comment_thread_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thread",
            old_name="contetnt",
            new_name="content",
        ),
    ]
