# Generated by Django 4.2.3 on 2023-09-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertease", "0011_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amenities",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
