# Generated by Django 4.2.3 on 2023-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "propertease",
            "0012_alter_property_amenities_alter_property_bathrooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amenities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
